# This is a basic workflow to help you get started with Actions

name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.5

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2

    - name: do autosidebar
      run: |
       cd ./docs
       node ./auto.js
       ls

    - uses: stefanzweifel/git-auto-commit-action@v5
    
    #- name: Commit changes
    # uses: EndBug/add-and-commit@v4
    #  with:
    #    author_name: GITHUB_GENERATOR
    #    message: "AUTO GENERATE sidebar"
    #    add: "*.md"
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.autosidebar }}
    #    CI: true
          
    # - name: upload   files to OSS
    #   uses:   fangbinwei/aliyun-oss-website-action@v1
    #   with:
    #     accessKeyId:   ${{ secrets.AKID }}
    #     accessKeySecret: ${{ secrets.AKS }}
    #     bucket:   opencs
    #     endpoint:   https://oss-cn-hongkong.aliyuncs.com
    #     folder:   ./docs
